<?php

namespace AppBundle\Repository;

/**
 * AvtomobileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvtomobileRepository extends \Doctrine\ORM\EntityRepository
{
}
