<?php

namespace AppBundle\Repository;

/**
 * Cars_descriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cars_descriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
