<?php

namespace AppBundle\Repository;

/**
 * Cars_optionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cars_optionRepository extends \Doctrine\ORM\EntityRepository
{
}
