<?php

namespace AppBundle\Repository;

/**
 * DriversRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriversRepository extends \Doctrine\ORM\EntityRepository
{
}
