<?php

namespace AppBundle\Repository;

/**
 * FillingChecksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FillingChecksRepository extends \Doctrine\ORM\EntityRepository
{
}
