<?php

namespace AppBundle\Repository;

/**
 * SmartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmartRepository extends \Doctrine\ORM\EntityRepository
{
}
