<?php

namespace AppBundle\Repository;

/**
 * WaybillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaybillRepository extends \Doctrine\ORM\EntityRepository
{
}
