<?php

namespace AppBundle\Repository;

/**
 * WayBillsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WayBillsRepository extends \Doctrine\ORM\EntityRepository
{
}
