app:
    resource: '@AppBundle/Controller/'
    type: annotation

addCarsDescription:
    path:     /addCarsDescription
    defaults: { _controller: AppBundle:Setting:addCarsDescription }

addCarsOption:
    path:     /addCarsOption
    defaults: { _controller: AppBundle:Setting:addCarsOption }

addDriver:
    path:     /addDriver
    defaults: { _controller: AppBundle:Setting:addDriver }

addFillingCheck:
    path:     /addFillingCheck
    defaults: { _controller: AppBundle:Setting:addFillingCheck }

addSmart:
    path:     /addSmart
    defaults: { _controller: AppBundle:Setting:addSmart }

addWayBill:
    path:     /addWayBill
    defaults: { _controller: AppBundle:Setting:addWayBill }