AppBundle\Entity\Avtomobile:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AvtomobileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        numberavto:
            type: string
            length: '50'
            unique: true
        nameavto:
            type: string
            length: '20'
            unique: true
        yearcar:
            type: date
        color:
            type: string
            nullable: true
            length: '20'
    lifecycleCallbacks: {  }
    oneToMany:
        waybills:
            targetEntity: Waybill
            mappedBy: carNumber